### ISSUE TITLE
Bad builds

### ISSUE THREAD

**Issue by CardealRusso** [ungoogled-software/ungoogled-chromium-portablelinux#147]
libffi8 and libpulse as depedency is bad

**Comment by CardealRusso** [comment]
since there is no response from the maintainer, I will unfortunately migrate to normal chromium, where the current binaries do not depend on pulse

**Comment by networkException** [comment]
@clickot do you have any idea what this could be?

**Comment by clickot** [comment]
@CardealRusso could you please describe in more detail what the problem is you address? I didn't change anything on the build procedure i execute when producing the binaries for some releases now..

**Comment by CardealRusso** [comment]
> @CardealRusso could you please describe in more detail what the problem is you address? I didn't change anything on the build procedure i execute when producing the binaries for some releases now..

Thanks for answering.

Basically all binaries compiled from version 116 onwards are using libffi 8 instead of 7 and, worse, they are being compiled with pulseaudio.

All other releases (I'm using RobRich's Chromium 120) don't make use of either.
```
ungoogled-chromium_118.0.5993.70-1.1_linux$ ldd chrome | grep found
	libffi.so.8 => not found
	libpulse.so.0 => not found
```

The latest commit on flags.gn suggests adding pulseaudio
https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/blob/ac70f0828c5bca6dc95e8850492513ccae4b5770/flags.gn#L13

not sure about the libffi8 but for sure comes on the same commit

**Comment by PF4Public** [comment]
> libffi 8 instead of 7

So why is it bad?

**Comment by CardealRusso** [comment]
> > libffi 8 instead of 7
> 
> So why is it bad?
I personally believe that it is not good practice to use a library when absolutely no other build does. But if you want to keep ffi8, then it doesn't make sense to remove pulseaudio. Because anyone who doesn't mind having to update libffi just for this chromium build and nothing else on their computer, certainly won't mind installing libpulse either.

**Comment by PF4Public** [comment]
>All other releases (I'm using RobRich's Chromium 120) don't make use of either.
>when absolutely no other build does

I'm sorry, but these statements are false.
https://github.com/RobRich999/Chromium_Clang/releases/tag/v120.0.6066.0-r1209773-linux64-deb-avx2
```
ldd opt/chromium.org/chromium-unstable/chrome|grep ffi
	libffi.so.8 => /usr/lib64/libffi.so.8 (0x00007fd5811af000)
```

Lets look at it from a different angle. [Debian stable has libffi8](https://packages.debian.org/bookworm/libffi8). [Arch has libffi8](https://gitlab.archlinux.org/archlinux/packaging/packages/libffi/-/blob/main/PKGBUILD?ref_type=heads). [Gentoo has libffi8](https://packages.gentoo.org/packages/dev-libs/libffi). There is no reason we couldn't expect libffi8 to be installable and/or present on the target system.

**Comment by CardealRusso** [comment]
> > All other releases (I'm using RobRich's Chromium 120) don't make use of either.
> > when absolutely no other build does
> 
> I'm sorry, but these statements are false. https://github.com/RobRich999/Chromium_Clang/releases/tag/v120.0.6066.0-r1209773-linux64-deb-avx2
> 
> ```
> ldd opt/chromium.org/chromium-unstable/chrome|grep ffi
> 	libffi.so.8 => /usr/lib64/libffi.so.8 (0x00007fd5811af000)
> ```
> 
> Lets look at it from a different angle. [Debian stable has libffi8](https://packages.debian.org/bookworm/libffi8). [Arch has libffi8](https://gitlab.archlinux.org/archlinux/packaging/packages/libffi/-/blob/main/PKGBUILD?ref_type=heads). [Gentoo has libffi8](https://packages.gentoo.org/packages/dev-libs/libffi). There is no reason we couldn't expect libffi8 to be installable and/or present on the target system.

This is not a false statement, please behave yourself, this is not a dispute.

I'm using the binary available at https://chromium.woolyss.com/

sha1: 1dc428b0671a90e962ae9c7723b8dd7a9f5a1296.(virus?) - chromium-browser-unstable_120.0.6066.0-1_amd64.deb

https://github.com/RobRich999/Chromium_Clang/releases/download/v120.0.6066.0-r1209773-linux64-deb-avx2/chromium-browser-unstable_120.0.6066.0-1_amd64.deb

And not yesterday's release

libffi.so.7 => /usr/local/lib/libffi.so.7 (0x00007f53b135a000)

**Comment by PF4Public** [comment]
> this is not a dispute

In that case I'm glad you managed to find a solution to the issue you reported.

**Comment by CardealRusso** [comment]
> > this is not a dispute
> 
> In that case I'm glad you managed to find a solution to the issue you reported.

You unfairly claim that I'm being false, and I rightly claim that you're being stupid by ignoring versions and comparing something released yesterday.

**Comment by porteux** [comment]
@PF4Public, I appreciate your work on this project, but [official Chromium](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F$1219663%2Fchrome-linux.zip?alt=media) is the bleeding edge version (`121.0.6106.0 (Developer Build)`) and it doesn't require libffi 8, but libffi 7.

When you build using this new version you're preventing countless users from enjoying your project simply because many distros (including latest versions) haven't updated libffi. And since there's no good reason to force this new version of libffi, I believe it would be better to just build Chromium against libffi 7.

Thanks!

**Comment by CardealRusso** [comment]
@porteux I think you should ignore @PF4Public's witless messages as much as @clickot did in the commit  ec016af407fbcdbd6cc2b64b727a865a2c7f16d1

**Comment by networkException** [comment]
I stand behind and believe that involved platform maintainers and core team members acted within the few requirements there are for their, completely voluntary work.

Our runtime requirements should generally align with vanilla chromium, is this the case (now, after the referenced commit)?

**Comment by clickot** [comment]
@networkException the dep to libpulse is removed (since it may be switched off by a gn flag), but the chrome binary still depends on libffi 8 (an according gn flag that seemed promising did not have the desired effect). I don't know how to change this, it is a dep that comes from the debian:bookworm builder image. Building with debian:bullseye is no longer possible since some 114.x (too old glibc), so i do not have a solution here.

btw: i was not part of the "discussion" here, but i dislike calling people stupid, witless or questioning their "moral" in a context of voluntary work. I made the commit (trying to solve the problem for the next release) and nobody else.

**Comment by porteux** [comment]
@clickot, thanks for the reply.

Since you mentioned glibc, this is another issue when trying to run your recent Chromium builds on some distros that haven't updated to 2.34. This is what I get if I fix the libffi issue:

```
chromium: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by chromium)
chromium: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by chromium)
```

Not only there is more than one version of glibc, but it's also newer than it should for better compatibility. Again, in official Chromium built by Google they're still providing support for older glibc.

Not sure if this is possible, but maybe you could build Chromium using a previous version of Debian on a VM. :)

**Comment by clickot** [comment]
@porteux : as i mentioned above, i was not able to build chromium up from 114.x with an older debian (bullseye) since the chromium code itself didn't compile anymore with the glibc (and maybo other c-libs) versions there and had to switch to the current stable version (bookworm). And there we get the  libffi8 dep....
That's why i do not realy have an idea to get around this

**Comment by PF4Public** [comment]
It might be possible via using `use_sysroot=true`, but this might require a lot of changes in order to make it work in the end.

**Comment by clickot** [comment]
@PF4Public btw: do you know if (and where) there is some kind of documentation of all these gn flags and what they actually do? Try and error is not very efficient regarding the build times.. :)

**Comment by PF4Public** [comment]
For this particular flag [the documentation](https://chromium.googlesource.com/chromium/src/+/main/docs/linux/sysroot.md) would be the best point to start. Other than that I gravitated to just [poking the sources](https://source.chromium.org/chromium/chromium/src/+/main:build/config/sysroot.gni;l=22?q=use_sysroot&sq=&ss=chromium%2Fchromium%2Fsrc) as this (most of the time) immediately shows _where_ and _how_ those flags are actually used.

**Comment by clickot** [comment]
@PF4Public : Thank you very much!

**Comment by clickot** [comment]
@porteux I managed to do the latest build of ungoogled-chromium using the sysroot feature and debian:bullseye builder image, so the result runs at least on ubuntu 20.04 and potentially others with "older" libs. If you want to give it a try:
https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/tag/119.0.6045.123-1

@PF4Public thanks again for your valuable hints
