### ISSUE TITLE
is cfi enabled in this build?

### ISSUE THREAD

**Issue by pony-montana** [ungoogled-software/ungoogled-chromium-portablelinux#152]
I'm not an expert and I'm struggling find this information exploring the codebase. 
There is the issue #148 that seems to be a problem with cfi, but in flags.gn I dont find is_cfi=true and use_cfi_icall=true, use_cfi_cast=true, use_thin_lto=true.
Are other flags grabbed from other location than flags.gn during compilation? Or is just that cfi is not enabled in this build?

**Comment by clickot** [comment]
the gn flags in this project (contained in the file `flags.gn`) are combined with the ones defined in `flags.gn` from the `ungoogled-chromium` repo. In both I don't find the properties you're looking for, so I suppose cfi is not enabled in this build.
As I stated in issue [https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/148] I had several problems during compilation with clang-17 that i didn't investigate further (so i don't know if cfi problems where included) but switched to clang-18 which worked for me.

**Comment by PF4Public** [comment]
> it could be well supported and not so problematic

As long as you build exactly like Google does. IIRC cfi requires clang, thinlto and libc++ instead of libstdc++.

>Is something that could be interesting to implement?

Some Gentoo folks use cfi with ungoogled-chromium — that's for sure. So it is doable.

>I don't know how much is the effectiveness

cfi could detect problematic code in Chromium, but apart from that I have my doubts on its effectiveness in other domains. Besides, do not expect catching such a bug yourself, most of the issues are likely to be caught by Google beforehead.

**Comment by clickot** [comment]
@PF4Public thanks for your comment :)
@pony-montana is that sufficient for you? If so would you mind closing this issue?

**Comment by pony-montana** [comment]
@clickot yes, for me it is sufficient 👍
