### ISSUE TITLE
ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by anchev** [ungoogled-software/ungoogled-chromium-portablelinux#2]
I don't know if this is the same issue as discussed in https://github.com/Eloston/ungoogled-chromium/issues/519#issue-363254814.

Starting `chrome` from command line always shows:

```
[12047:12047:0325/153826.065129:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
```
This has been happening for many months (i.e. not something new).

**Comment by Eloston** [comment]
I believe it's the same issue. I have also seen this across multiple versions in all Linux builds of ungoogled-chromium.

In fact, it seems to be a general Chromium issue. There is some enlightening discussion here:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433
* https://bugs.chromium.org/p/chromium/issues/detail?id=264818

**Comment by sahin52** [comment]
This issue still keeps on. Pls reopen it

**Comment by 3y3p4tch** [comment]
After a bit of searching here and there, It looks like the issue has been fixed upstream.
A short fix for the issue is to set `MESA_GLSL_CACHE_DISABLE`=true. (Using brave here; after setting env var, can verify that `brave://gpu` shows Sandboxed=true for GPU)
Relevant bugs are: https://bugs.chromium.org/p/chromium/issues/detail?id=924759, https://bugs.chromium.org/p/chromium/issues/detail?id=996455
Relevant commit: https://chromium.googlesource.com/chromium/src/+/c45894a002e2d04ccffbd60c568a247fddf60f0e
