### ISSUE TITLE
Upgrade to chroumium 89

### ISSUE THREAD

**Issue by Raviu56** [ungoogled-software/ungoogled-chromium-portablelinux#90]
There are critical security issues on current 87 version.
Windows, ArchLinux and manjaro builds have been upgraded https://ungoogled-software.github.io/ungoogled-chromium-binaries/ 
Please upgrade this build as soon as possible.

**Comment by markwylde** [comment]
Since this repo isn't updated much, I've tried to come up with a solution to building an AppImage from the debian installation.

It works for me, but since I'm on a Debian instance it might be easier I guess.

Could you give it a go:

From Source: https://github.com/one2build/ungoogled-chromium
My Release: https://github.com/one2build/ungoogled-chromium/releases/tag/ungoogled-89.0.4389

This works by building the Ungoogled Chromium release for debian, then extracting the `*.deb` files and bundling them using [pkg2appimage](https://github.com/AppImage/pkg2appimage).

**Comment by markwylde** [comment]
I've just spun up a manjaro iso vm, and can confirm my release works. Or at least, it works now.

I had missed a few lib's when building the pkg2appimage.

**Comment by Eloston** [comment]
Usually this repo isn't updated because there isn't much work needed to get this working on a new version. It's very vanilla Chromium.

Maybe we could automate it... #91

**Comment by Eloston** [comment]
Updated to `90.0.4430.85-1.1`
